services:
  - type: web
    name: twilio-poc-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ACCOUNT_SID
        sync: false
      - key: AUTH_TOKEN
        sync: false
      - key: TWILIO_NUMBER
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: FRONTEND_URL
        sync: false
